name: Deploy frontend to Azure Storage Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload frontend to $web
        uses: azure/CLI@v1
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name staccountgaelgallery \
              --auth-mode key \
              --account-key "$AZURE_STORAGE_KEY" \
              --destination '$web' \
              --source frontend \
              --overwrite

